# Generated by Django 4.0 on 2022-11-10 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_blogtext_blog_blogdescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('Blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key='True', serialize=False, to='blog.blog')),
                ('Comment', models.TextField(max_length=250)),
            ],
        ),
    ]
